use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};
use std::process;
use std::sync::Arc;

use anyhow::{Context, Result, bail};
use clap::Parser;
use tokio::task::JoinSet;

mod artifacts;
mod cli;
mod config;
mod git;
mod git_url;
mod npm;
mod platform;
mod publish;
mod template;

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let cli::Cargo::Npm(npm) = cli::Cargo::parse();
    let result = match npm.command {
        cli::Command::Generate(args) => cmd_generate(&args),
        cli::Command::Publish(args) => cmd_publish(&args).await,
    };
    if let Err(e) = result {
        eprintln!("error: {e:#}");
        process::exit(1);
    }
}

fn cmd_generate(args: &cli::GenerateArgs) -> Result<()> {
    let build = config::load(config::LoadOpts {
        manifest_path: args.common.manifest_path.clone(),
        package: args.common.package.clone(),
        workspace: args.common.workspace,
        exclude: args.common.exclude.clone(),
        cli_targets: args.target.clone(),
        use_cargo_config: true,
        target_dir: args.target_dir.clone(),
        out_dir: args.common.out_dir.clone(),
    })?;

    if build.jobs.is_empty() {
        bail!("no binary crates found");
    }

    if args.clean && build.output_dir.exists() {
        check_safe_to_clean(&build.output_dir, &build.jobs)?;
        fs::remove_dir_all(&build.output_dir).with_context(|| {
            format!(
                "failed to clean output directory {}",
                build.output_dir.display()
            )
        })?;
    }
    fs::create_dir_all(&build.output_dir)?;

    let mut exclude_entries: Vec<PathBuf> = Vec::new();
    let mut used_pkg_names: HashSet<String> = HashSet::new();

    for job in build.jobs {
        if !used_pkg_names.insert(job.name.clone()) {
            bail!(
                "package name collision: '{}' would be generated by multiple packages",
                job.name
            );
        }

        if args.stub {
            npm::generate_main_package(&build.output_dir, &job, &[])?;
            continue;
        }

        let targets = if args.infer_targets {
            artifacts::infer_targets(&job.bins, &build.target_dir)?
        } else if job.targets.is_empty() {
            bail!(
                "no targets configured - add [package.metadata.npm] targets to Cargo.toml, \
                 pass --target, or use --infer-targets to discover built binaries"
            );
        } else {
            job.targets.clone()
        };

        let (platforms, unrecognised) = platform::resolve_platforms(&targets)?;
        if !unrecognised.is_empty() {
            if job.targets_explicit {
                bail!(
                    "unrecognised target triple(s) {} - \
                     cargo-npm does not know how to map them to npm platforms",
                    unrecognised.join(", ")
                );
            }
            eprintln!(
                "warning: skipping unrecognised target triple(s) {} - \
                 cargo-npm does not know how to map them to npm platforms",
                unrecognised.join(", ")
            );
        }
        if platforms.is_empty() {
            bail!("none of the configured targets can be mapped to supported npm platforms");
        }

        let mut platform_pkgs = Vec::new();
        for platform in &platforms {
            let pkg_name = npm::platform_package_name(&job.prefix, platform);
            if !used_pkg_names.insert(pkg_name.clone()) {
                bail!(
                    "platform package name collision: '{pkg_name}' would be generated by multiple \
                     packages (package: '{}', prefix: '{}')",
                    job.name,
                    job.prefix,
                );
            }

            for bin_name in &job.bins {
                let bin_file = if platform.os == platform::Os::Win32 {
                    format!("{bin_name}.exe")
                } else {
                    bin_name.clone()
                };
                exclude_entries.push(build.output_dir.join(&pkg_name).join(bin_file));
            }

            let pkg_dir = build.output_dir.join(&pkg_name);
            platform_pkgs.push(npm::generate_platform_package(
                &build.output_dir,
                platform,
                &pkg_name,
                &job,
            )?);
            artifacts::copy_bins(&job.bins, &build.target_dir, platform, &pkg_dir)?;
        }

        npm::generate_main_package(&build.output_dir, &job, &platform_pkgs)?;
    }

    git::update_git_exclude(&build.output_dir, &exclude_entries)?;

    println!("Generated npm packages in {}", build.output_dir.display());

    Ok(())
}

async fn cmd_publish(args: &cli::PublishArgs) -> Result<()> {
    publish::which_npm()?;

    let build = config::load(config::LoadOpts {
        manifest_path: args.common.manifest_path.clone(),
        package: args.common.package.clone(),
        workspace: args.common.workspace,
        exclude: args.common.exclude.clone(),
        cli_targets: Vec::new(),
        use_cargo_config: false,
        target_dir: None,
        out_dir: args.common.out_dir.clone(),
    })?;

    if build.jobs.is_empty() {
        bail!("no binary crates found");
    }

    let packages: Vec<publish::Package> = build
        .jobs
        .iter()
        .map(|job| publish::prepare(&build.output_dir, job))
        .collect::<Result<_>>()?;

    let extra_args = Arc::new(args.npm_args.clone());
    let mut job_set = JoinSet::new();
    for package in packages {
        let extra_args = Arc::clone(&extra_args);
        job_set.spawn(async move { publish::publish(package, extra_args).await });
    }
    let mut errors: Vec<anyhow::Error> = Vec::new();
    while let Some(res) = job_set.join_next().await {
        match res {
            Ok(Ok(())) => {}
            Ok(Err(e)) => errors.push(e),
            Err(e) => errors.push(anyhow::Error::from(e)),
        }
    }
    match errors.len() {
        0 => Ok(()),
        1 => Err(errors.remove(0)),
        n => {
            let msg = errors
                .iter()
                .map(|e| format!("  - {e:#}"))
                .collect::<Vec<_>>()
                .join("\n");
            bail!("{n} publish tasks failed:\n{msg}")
        }
    }
}

fn check_safe_to_clean(output_dir: &Path, jobs: &[config::Job]) -> Result<()> {
    let cwd = std::env::current_dir().context("failed to resolve current directory")?;
    if cwd.starts_with(output_dir) {
        bail!(
            "refusing to clean output directory {} as it contains the current working directory",
            output_dir.display()
        );
    }
    for job in jobs {
        if job.crate_dir.starts_with(output_dir) {
            bail!(
                "refusing to clean output directory {} as it contains package directory {}",
                output_dir.display(),
                job.crate_dir.display()
            );
        }
    }
    Ok(())
}
